# Generated by Django 6.0.2 on 2026-03-17 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('qid', models.AutoField(primary_key=True, serialize=False)),
                ('qtext', models.CharField(max_length=250)),
                ('op1', models.CharField(max_length=250)),
                ('op2', models.CharField(max_length=250)),
                ('op3', models.CharField(max_length=250)),
                ('op4', models.CharField(max_length=250)),
                ('correct_ans', models.CharField(max_length=250)),
                ('subject', models.CharField(max_length=250)),
            ],
        ),
    ]
